server:
  port: 8081
bezkoder:
  openapi:
    dev-url: http://localhost:8081
springdoc:
  swagger-ui:
    path: /
  packages-to-scan: run.innkeeper.api

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_AUTH_ID}
            client-secret: ${GOOGLE_AUTH_SECRET}
            scope: openid,email,profile
            redirect-uri: http://${DOMAIN_PORT}/login/oauth2/code/google
        provider:
          google:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs