apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-role
subjects:
  - kind: ServiceAccount
    name: cluster-admin-account
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-operator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-operator
  template:
    metadata:
      labels:
        app: java-operator
    spec:
      serviceAccountName: cluster-admin-account
      containers:
        - name: java-operator-container
          env:
            - name: GOOGLE_AUTH_ID
              value: "<string>"
            - name: GOOGLE_AUTH_SECRET
              value: "<string>"
            - name: DOMAIN_PORT
              value: "https://<domain>"
            - name: BEARER_TOKEN
              value: "<string>"
          imagePullPolicy: Always
          image: ghcr.io/innkeeperdevops/java-operator:main
---
apiVersion: v1
kind: Service
metadata:
  name: java-operator
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: java-operator
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: java-operator
spec:
  gatewayClassName: istio
  listeners:  # Use GatewayClass defaults for listener definition.
    - name: http
      protocol: HTTP
      port: 8081
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: java-operator
spec:
  parentRefs:
    - name: java-operator
  hostnames:
    - "<domain>"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: java-operator
          port: 8081